//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.225.
// 
#pragma warning disable 1591

namespace EventMonitoringAdmin.UserManagement {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserSoap", Namespace="http://ICAA.EventMonitoringService.org/")]
    public partial class User : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback addNewUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMachinesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getUserDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifyUserSettingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback addSuppressedLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback deleteSuppressedLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback getAllSuppressedLogOperationCompleted;
        
        private System.Threading.SendOrPostCallback modifySuppressedLogListOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public User() {
            this.Url = global::EventMonitoringAdmin.Properties.Settings.Default.EventMonitoringAdmin_UserManagement_User;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event addNewUserCompletedEventHandler addNewUserCompleted;
        
        /// <remarks/>
        public event getMachinesCompletedEventHandler getMachinesCompleted;
        
        /// <remarks/>
        public event getUserDetailsCompletedEventHandler getUserDetailsCompleted;
        
        /// <remarks/>
        public event modifyUserSettingsCompletedEventHandler modifyUserSettingsCompleted;
        
        /// <remarks/>
        public event addSuppressedLogCompletedEventHandler addSuppressedLogCompleted;
        
        /// <remarks/>
        public event deleteSuppressedLogCompletedEventHandler deleteSuppressedLogCompleted;
        
        /// <remarks/>
        public event getAllSuppressedLogCompletedEventHandler getAllSuppressedLogCompleted;
        
        /// <remarks/>
        public event modifySuppressedLogListCompletedEventHandler modifySuppressedLogListCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ICAA.EventMonitoringService.org/addNewUser", RequestNamespace="http://ICAA.EventMonitoringService.org/", ResponseNamespace="http://ICAA.EventMonitoringService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultSet addNewUser(string userName, string firstName, string lastName, string primaryEmail, string secondaryEmail, string[] machines) {
            object[] results = this.Invoke("addNewUser", new object[] {
                        userName,
                        firstName,
                        lastName,
                        primaryEmail,
                        secondaryEmail,
                        machines});
            return ((ResultSet)(results[0]));
        }
        
        /// <remarks/>
        public void addNewUserAsync(string userName, string firstName, string lastName, string primaryEmail, string secondaryEmail, string[] machines) {
            this.addNewUserAsync(userName, firstName, lastName, primaryEmail, secondaryEmail, machines, null);
        }
        
        /// <remarks/>
        public void addNewUserAsync(string userName, string firstName, string lastName, string primaryEmail, string secondaryEmail, string[] machines, object userState) {
            if ((this.addNewUserOperationCompleted == null)) {
                this.addNewUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddNewUserOperationCompleted);
            }
            this.InvokeAsync("addNewUser", new object[] {
                        userName,
                        firstName,
                        lastName,
                        primaryEmail,
                        secondaryEmail,
                        machines}, this.addNewUserOperationCompleted, userState);
        }
        
        private void OnaddNewUserOperationCompleted(object arg) {
            if ((this.addNewUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addNewUserCompleted(this, new addNewUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ICAA.EventMonitoringService.org/getMachines", RequestNamespace="http://ICAA.EventMonitoringService.org/", ResponseNamespace="http://ICAA.EventMonitoringService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultMachines getMachines() {
            object[] results = this.Invoke("getMachines", new object[0]);
            return ((ResultMachines)(results[0]));
        }
        
        /// <remarks/>
        public void getMachinesAsync() {
            this.getMachinesAsync(null);
        }
        
        /// <remarks/>
        public void getMachinesAsync(object userState) {
            if ((this.getMachinesOperationCompleted == null)) {
                this.getMachinesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMachinesOperationCompleted);
            }
            this.InvokeAsync("getMachines", new object[0], this.getMachinesOperationCompleted, userState);
        }
        
        private void OngetMachinesOperationCompleted(object arg) {
            if ((this.getMachinesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMachinesCompleted(this, new getMachinesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ICAA.EventMonitoringService.org/getUserDetails", RequestNamespace="http://ICAA.EventMonitoringService.org/", ResponseNamespace="http://ICAA.EventMonitoringService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserDetails getUserDetails(string strUsername) {
            object[] results = this.Invoke("getUserDetails", new object[] {
                        strUsername});
            return ((UserDetails)(results[0]));
        }
        
        /// <remarks/>
        public void getUserDetailsAsync(string strUsername) {
            this.getUserDetailsAsync(strUsername, null);
        }
        
        /// <remarks/>
        public void getUserDetailsAsync(string strUsername, object userState) {
            if ((this.getUserDetailsOperationCompleted == null)) {
                this.getUserDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetUserDetailsOperationCompleted);
            }
            this.InvokeAsync("getUserDetails", new object[] {
                        strUsername}, this.getUserDetailsOperationCompleted, userState);
        }
        
        private void OngetUserDetailsOperationCompleted(object arg) {
            if ((this.getUserDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getUserDetailsCompleted(this, new getUserDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ICAA.EventMonitoringService.org/modifyUserSettings", RequestNamespace="http://ICAA.EventMonitoringService.org/", ResponseNamespace="http://ICAA.EventMonitoringService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultSet modifyUserSettings(string userName, string firstName, string lastName, string primaryEmail, string secondaryEmail, string[] machines) {
            object[] results = this.Invoke("modifyUserSettings", new object[] {
                        userName,
                        firstName,
                        lastName,
                        primaryEmail,
                        secondaryEmail,
                        machines});
            return ((ResultSet)(results[0]));
        }
        
        /// <remarks/>
        public void modifyUserSettingsAsync(string userName, string firstName, string lastName, string primaryEmail, string secondaryEmail, string[] machines) {
            this.modifyUserSettingsAsync(userName, firstName, lastName, primaryEmail, secondaryEmail, machines, null);
        }
        
        /// <remarks/>
        public void modifyUserSettingsAsync(string userName, string firstName, string lastName, string primaryEmail, string secondaryEmail, string[] machines, object userState) {
            if ((this.modifyUserSettingsOperationCompleted == null)) {
                this.modifyUserSettingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifyUserSettingsOperationCompleted);
            }
            this.InvokeAsync("modifyUserSettings", new object[] {
                        userName,
                        firstName,
                        lastName,
                        primaryEmail,
                        secondaryEmail,
                        machines}, this.modifyUserSettingsOperationCompleted, userState);
        }
        
        private void OnmodifyUserSettingsOperationCompleted(object arg) {
            if ((this.modifyUserSettingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifyUserSettingsCompleted(this, new modifyUserSettingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ICAA.EventMonitoringService.org/addSuppressedLog", RequestNamespace="http://ICAA.EventMonitoringService.org/", ResponseNamespace="http://ICAA.EventMonitoringService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultUser addSuppressedLog(string operation, string chUsername, LogDetails[] log) {
            object[] results = this.Invoke("addSuppressedLog", new object[] {
                        operation,
                        chUsername,
                        log});
            return ((resultUser)(results[0]));
        }
        
        /// <remarks/>
        public void addSuppressedLogAsync(string operation, string chUsername, LogDetails[] log) {
            this.addSuppressedLogAsync(operation, chUsername, log, null);
        }
        
        /// <remarks/>
        public void addSuppressedLogAsync(string operation, string chUsername, LogDetails[] log, object userState) {
            if ((this.addSuppressedLogOperationCompleted == null)) {
                this.addSuppressedLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddSuppressedLogOperationCompleted);
            }
            this.InvokeAsync("addSuppressedLog", new object[] {
                        operation,
                        chUsername,
                        log}, this.addSuppressedLogOperationCompleted, userState);
        }
        
        private void OnaddSuppressedLogOperationCompleted(object arg) {
            if ((this.addSuppressedLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addSuppressedLogCompleted(this, new addSuppressedLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ICAA.EventMonitoringService.org/deleteSuppressedLog", RequestNamespace="http://ICAA.EventMonitoringService.org/", ResponseNamespace="http://ICAA.EventMonitoringService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultUser deleteSuppressedLog(string username, LogDetails[] log) {
            object[] results = this.Invoke("deleteSuppressedLog", new object[] {
                        username,
                        log});
            return ((resultUser)(results[0]));
        }
        
        /// <remarks/>
        public void deleteSuppressedLogAsync(string username, LogDetails[] log) {
            this.deleteSuppressedLogAsync(username, log, null);
        }
        
        /// <remarks/>
        public void deleteSuppressedLogAsync(string username, LogDetails[] log, object userState) {
            if ((this.deleteSuppressedLogOperationCompleted == null)) {
                this.deleteSuppressedLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OndeleteSuppressedLogOperationCompleted);
            }
            this.InvokeAsync("deleteSuppressedLog", new object[] {
                        username,
                        log}, this.deleteSuppressedLogOperationCompleted, userState);
        }
        
        private void OndeleteSuppressedLogOperationCompleted(object arg) {
            if ((this.deleteSuppressedLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.deleteSuppressedLogCompleted(this, new deleteSuppressedLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ICAA.EventMonitoringService.org/getAllSuppressedLog", RequestNamespace="http://ICAA.EventMonitoringService.org/", ResponseNamespace="http://ICAA.EventMonitoringService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public resultUser getAllSuppressedLog(string userName) {
            object[] results = this.Invoke("getAllSuppressedLog", new object[] {
                        userName});
            return ((resultUser)(results[0]));
        }
        
        /// <remarks/>
        public void getAllSuppressedLogAsync(string userName) {
            this.getAllSuppressedLogAsync(userName, null);
        }
        
        /// <remarks/>
        public void getAllSuppressedLogAsync(string userName, object userState) {
            if ((this.getAllSuppressedLogOperationCompleted == null)) {
                this.getAllSuppressedLogOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetAllSuppressedLogOperationCompleted);
            }
            this.InvokeAsync("getAllSuppressedLog", new object[] {
                        userName}, this.getAllSuppressedLogOperationCompleted, userState);
        }
        
        private void OngetAllSuppressedLogOperationCompleted(object arg) {
            if ((this.getAllSuppressedLogCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getAllSuppressedLogCompleted(this, new getAllSuppressedLogCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://ICAA.EventMonitoringService.org/modifySuppressedLogList", RequestNamespace="http://ICAA.EventMonitoringService.org/", ResponseNamespace="http://ICAA.EventMonitoringService.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResultSet modifySuppressedLogList(string chUsername, LogDetails[] log) {
            object[] results = this.Invoke("modifySuppressedLogList", new object[] {
                        chUsername,
                        log});
            return ((ResultSet)(results[0]));
        }
        
        /// <remarks/>
        public void modifySuppressedLogListAsync(string chUsername, LogDetails[] log) {
            this.modifySuppressedLogListAsync(chUsername, log, null);
        }
        
        /// <remarks/>
        public void modifySuppressedLogListAsync(string chUsername, LogDetails[] log, object userState) {
            if ((this.modifySuppressedLogListOperationCompleted == null)) {
                this.modifySuppressedLogListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnmodifySuppressedLogListOperationCompleted);
            }
            this.InvokeAsync("modifySuppressedLogList", new object[] {
                        chUsername,
                        log}, this.modifySuppressedLogListOperationCompleted, userState);
        }
        
        private void OnmodifySuppressedLogListOperationCompleted(object arg) {
            if ((this.modifySuppressedLogListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.modifySuppressedLogListCompleted(this, new modifySuppressedLogListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(resultUser))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultMachines))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ICAA.EventMonitoringService.org/")]
    public partial class ResultSet {
        
        private string stringResultTypeField;
        
        private string stringResultMessageField;
        
        private string stringResultDataField;
        
        /// <remarks/>
        public string stringResultType {
            get {
                return this.stringResultTypeField;
            }
            set {
                this.stringResultTypeField = value;
            }
        }
        
        /// <remarks/>
        public string stringResultMessage {
            get {
                return this.stringResultMessageField;
            }
            set {
                this.stringResultMessageField = value;
            }
        }
        
        /// <remarks/>
        public string stringResultData {
            get {
                return this.stringResultDataField;
            }
            set {
                this.stringResultDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ICAA.EventMonitoringService.org/")]
    public partial class LogDetails {
        
        private long eventIdField;
        
        private string sourceField;
        
        private System.DateTime dtGeneratedField;
        
        private string chUsernameField;
        
        private string typeField;
        
        /// <remarks/>
        public long eventId {
            get {
                return this.eventIdField;
            }
            set {
                this.eventIdField = value;
            }
        }
        
        /// <remarks/>
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime dtGenerated {
            get {
                return this.dtGeneratedField;
            }
            set {
                this.dtGeneratedField = value;
            }
        }
        
        /// <remarks/>
        public string chUsername {
            get {
                return this.chUsernameField;
            }
            set {
                this.chUsernameField = value;
            }
        }
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ICAA.EventMonitoringService.org/")]
    public partial class UserDetails {
        
        private string sUsernameField;
        
        private string sFirstnameField;
        
        private string sLastnameField;
        
        private string sPrimaryEmailField;
        
        private string sSecondaryEmailField;
        
        private string[] machinesField;
        
        /// <remarks/>
        public string sUsername {
            get {
                return this.sUsernameField;
            }
            set {
                this.sUsernameField = value;
            }
        }
        
        /// <remarks/>
        public string sFirstname {
            get {
                return this.sFirstnameField;
            }
            set {
                this.sFirstnameField = value;
            }
        }
        
        /// <remarks/>
        public string sLastname {
            get {
                return this.sLastnameField;
            }
            set {
                this.sLastnameField = value;
            }
        }
        
        /// <remarks/>
        public string sPrimaryEmail {
            get {
                return this.sPrimaryEmailField;
            }
            set {
                this.sPrimaryEmailField = value;
            }
        }
        
        /// <remarks/>
        public string sSecondaryEmail {
            get {
                return this.sSecondaryEmailField;
            }
            set {
                this.sSecondaryEmailField = value;
            }
        }
        
        /// <remarks/>
        public string[] machines {
            get {
                return this.machinesField;
            }
            set {
                this.machinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ICAA.EventMonitoringService.org/")]
    public partial class Machine {
        
        private string machineNameField;
        
        private string machineTypeField;
        
        /// <remarks/>
        public string machineName {
            get {
                return this.machineNameField;
            }
            set {
                this.machineNameField = value;
            }
        }
        
        /// <remarks/>
        public string machineType {
            get {
                return this.machineTypeField;
            }
            set {
                this.machineTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ICAA.EventMonitoringService.org/")]
    public partial class resultUser : ResultSet {
        
        private string userNameField;
        
        private System.Data.DataTable suppressedLogField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataTable suppressedLog {
            get {
                return this.suppressedLogField;
            }
            set {
                this.suppressedLogField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ICAA.EventMonitoringService.org/")]
    public partial class ResultMachines : ResultSet {
        
        private Machine[] machinesField;
        
        /// <remarks/>
        public Machine[] machines {
            get {
                return this.machinesField;
            }
            set {
                this.machinesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void addNewUserCompletedEventHandler(object sender, addNewUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getMachinesCompletedEventHandler(object sender, getMachinesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMachinesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMachinesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultMachines Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultMachines)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getUserDetailsCompletedEventHandler(object sender, getUserDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getUserDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getUserDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserDetails Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserDetails)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void modifyUserSettingsCompletedEventHandler(object sender, modifyUserSettingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifyUserSettingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modifyUserSettingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void addSuppressedLogCompletedEventHandler(object sender, addSuppressedLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addSuppressedLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addSuppressedLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void deleteSuppressedLogCompletedEventHandler(object sender, deleteSuppressedLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deleteSuppressedLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal deleteSuppressedLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getAllSuppressedLogCompletedEventHandler(object sender, getAllSuppressedLogCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getAllSuppressedLogCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getAllSuppressedLogCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public resultUser Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((resultUser)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void modifySuppressedLogListCompletedEventHandler(object sender, modifySuppressedLogListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class modifySuppressedLogListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal modifySuppressedLogListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResultSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResultSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591